name: Increment Counter on Push

on:
  push:
    branches: [main]

jobs:
  increment-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Check for existing counter value
        id: counter-check
        run: |
          if [[ -n "${{ github.event.repository.environment.COUNTER }}" ]]; then
            echo "::set-output name=counter::$((${{ github.event.repository.environment.COUNTER }} + 1))"
          else
            echo "::set-output name=counter::1"
          fi

      - name: Set counter environment variable
        run: |
          echo "COUNTER=${{ steps.counter-check.outputs.counter }}" >> $GITHUB_ENV






          


