name: Commit Counter and Check GitHub ENV

on:
  push:
    branches:
      - main

jobs:
  count-commits:
    name: Commit Counter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Count commits
        id: commit_count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "::set-output name=commit_count::$COMMIT_COUNT"

      - name: Store commit count
        run: echo "COMMIT_COUNT=${{ steps.commit_count.outputs.commit_count }}" >> $GITHUB_ENV
        
      # Optionally, you can store the count in a file
      # - name: Store commit count in file
      #   run: echo "${{ steps.commit_count.outputs.commit_count }}" > commit_count.txt

  check-env:
    name: Check GitHub ENV
    runs-on: ubuntu-latest
    needs: count-commits
    steps:
      - name: Show GitHub ENV
        run: echo "$GITHUB_ENV"
